title="mc-to-kafka"
[main]
serverIp="127.0.0.1"
serverPort=9191
mainLogPath="/tmp/ho.log"
mainLogModel=3 

[kafkas]
    [kafkas.xmeta]
    brokers=["tt.com:19094"]
    topic="test_mc"
    group=""
    sslEnable=false
    user=""
    password=""
    producerOn=true
    [kafkas.xdata]
    brokers=["tt.com:19094"]
    topic="test_mc2"
    group=""
    sslEnable=false
    user=""
    password=""
    producerOn=true
