title="mc-to-kafka"
[main]
ServerIp="127.0.0.1"
ServerPort=9190
MainLogPath="/tmp/ho.log"
[kafkas]
    [kafkas.bridgeWrite]
    brockers=""
    topic="common_test"
    group=""
    user="adBusiness"
    password=""
    fromBeginning=false