title="kafka-to-kafka"
[main]
serverIp="127.0.0.1"
serverPort=9193
mainLogPath="/tmp/ho_kafka_2_kafka"
mainLogModel=3
showSaramaDebug=true
[kafkas]
    [kafkas.test_mc]
    brokers=["tt.com:18888"]
    topic="test_mc"
    group="test"
    sslEnable=false
    user=""
    password=""
    producerOn=false
    [kafkas.test_mc2]
    brokers=["tt.com:18888"]
    topic="test_mc2"
    group=""
    sslEnable=false
    user=""
    password=""
    producerOn=true
